config/routes.rb
Rails.application.routes.draw do
  root 'testers#index'
  resources :testers, only: %i[index create]
  resources :cards
  resources :users
  resources :decks
  resources :user_sessions, only: %i[new create destroy]
  get 'login', to: 'user_sessions#new', as: :login
  post 'logout', to: 'user_sessions#destroy', as: :logout

  scope '/oauth' do
    post 'callback', to: 'oauths#callback'
    get 'callback', to: 'oauths#callback'
    get ':provider', to: 'oauths#oauth', as: :auth_at_provider
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
# frozen_string_literal: true

class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/card.rb
# frozen_string_literal: true

class Card < ApplicationRecord
  mount_uploader :picture, PictureUploader
  before_create :set_review_date
  belongs_to :deck
  delegate :user, to: :deck
  validates :original_text, presence: true, length: { maximum: 50 }
  validates :translated_text, presence: true, length: { maximum: 50 }
  validate :check_not_equal

  def check_not_equal
    return unless original_text && translated_text
    if original_text.casecmp(translated_text).zero?
      errors.add(:translated_text, I18n.t('card.error.equal'))
    end
  end

  scope :out_of_time, -> { where("review_date <= ?", Time.current) }

  def self.random_card
    out_of_time.order('RANDOM()').take
  end

  private

  def set_review_date
    self.review_date = Time.current
  end
end

app/models/deck.rb
# frozen_string_literal: true

class Deck < ApplicationRecord
  belongs_to :user
  has_many :cards, dependent: :destroy
  validates :user_id, :name, presence: true
  validates :current, uniqueness: { scope: :user_id }, if: :current
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications
  has_many :decks, dependent: :destroy
  has_many :cards, through: :decks
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  def has_linked_github?
    authentications.where(provider: 'github').present?
  end

  def self.notify_training_card
    User.all.each do |user|
      if user.cards.out_of_time.any?
        NotificationsMailer.pending_cards(user).deliver_now
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login, except: [:not_authenticated]

  private

  def not_authenticated
    redirect_to login_path
    flash[:warning] = t('user.alert.log_in_first')
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :find_card, only: %i[show edit update destroy]

  def index
    @cards = current_user.cards.decorate
  end

  def new
    @card = current_user.cards.build.decorate
  end

  def show; end

  def create
    @card = current_user.cards.build(card_params).decorate
    if @card.save
      redirect_to cards_path
      flash[:info] = t('card.note.saved')
    else
      flash.now[:warning] = t('card.error.fail')
      render 'new'
    end
  end

  def edit; end

  def update
    if @card.update(card_params)
      redirect_to card_path(@card), notice: t('card.note.changed')
    else
      flash.now[:warning] = t('card.error.fail')
      render 'edit'
    end
  end

  def destroy
    @card.destroy
    redirect_to cards_path, notice: t('card.note.deleted')
  end

  private

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :picture, :remote_picture_url, :deck_id)
  end

  def find_card
    @card = current_user.cards.find_by(id: params[:id]).decorate
    redirect_to cards_path unless @card
  end
end

app/controllers/decks_controller.rb
# frozen_string_literal: true

class DecksController < ApplicationController
  before_action :set_deck, only: %i[show edit update destroy]

  def index
    @decks = current_user.decks
  end

  def new
    @deck = current_user.decks.build
  end

  def show; end

  def create
    @deck = current_user.decks.build(deck_params)
    if @deck.save
      redirect_to decks_path, notice: t('deck.note.created')
    else
      flash.now[:warning] = t('card.error.fail')
      render :new
    end
  end

  def edit; end

  def update
    if @deck.update(deck_params)
      redirect_to decks_path, notice: t('deck.note.edited')
    else
      flash.now[:warning] = t('card.error.fail')
      render :edit
    end
  end

  def destroy
    @deck.destroy
    redirect_to decks_path, notice: t('deck.note.deleted')
  end

  private

  def set_deck
    @deck = current_user.decks.find(params[:id])
  end

  def deck_params
    params.require(:deck).permit(:name, :current)
  end
end

app/controllers/oauths_controller.rb
# frozen_string_literal: true

class OauthsController < ApplicationController
  skip_before_action :require_login
  # sends the user on a trip to the provider,
  # and after authorizing there back to the callback url.
  def oauth
    login_at(auth_params[:provider])
  end

  def callback
    provider = auth_params[:provider]
    if @user = login_from(provider)
      redirect_to root_path, notice: "#{t('user.note.logged_from')} #{provider.titleize}!"
    else
      begin
        @user = create_from(provider)
        # NOTE: this is the place to add '@user.activate!' if you are using user_activation submodule

        reset_session
        auto_login(@user)
        redirect_to root_path, notice: "#{t('user.note.logged_from')} #{provider.titleize}!"
      rescue StandardError
        redirect_to root_path, alert: "#{t('user.alert.failed_from')} #{provider.titleize}!"
      end
    end
  end

  private

  def auth_params
    params.permit(:code, :provider)
  end
end

app/controllers/testers_controller.rb
# frozen_string_literal: true

class TestersController < ApplicationController
  def index
    @card = RandomCardQuery.new(current_user).call
  end

  def create
    @card = Card.find(params[:card_id]).decorate
    handle_check_result(CheckCard.new(@card, params[:answer]))
    redirect_back(fallback_location: testers_path)
  end

  def handle_check_result(tester)
    case tester.call
    when :correct
      flash[:info] = I18n.t('card.note.it_true')
    when :correct_with_one_typo
      flash[:info] = I18n.t('card.note.it_true_with_typo', answ: params[:answer], translate: @card.translated_text)
    when :incorrect_with_reset
      flash[:danger] = I18n.t('card.note.incorrect_with_reset', translate: @card.translated_text)
    when :incorrect
      flash[:warning] = I18n.t('card.note.incorrect', count: tester.attempts_left)
    end
  end
end

app/controllers/user_sessions_controller.rb
# frozen_string_literal: true

class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(@user, notice: t('user.note.log_in'))
    else
      flash.now[:warning] = t('user.note.log_in_false')
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: t('user.note.log_out'))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: %i[show edit update destroy]
  skip_before_action :require_login, only: %i[index new create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show; end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      UsersMailer.user_created(@user).deliver_now
      redirect_to users_path, notice: t('user.note.created')
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: t('user.note.updated')
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_form.html.haml
.row.justify-content-center
  = simple_form_for @card do |f|
    .field.text-center
      = f.input :original_text, label: false
      = f.input :translated_text, label: false
      = f.association :deck, collection: current_user.decks
      = @card.current_picture
      = f.input :picture
      = f.input :remote_picture_url, label: false
      %br= f.submit t('card.button.save'), class: "btn btn-primary"

app/views/cards/edit.html.haml
%h2= t 'card.title.editing'
= render 'form'

app/views/cards/index.html.haml
%table.table.table-sm
  %thead
    %tr
      %th{ scope:'col' }= t 'card.page.original'
      %th{ scope:'col' }= t 'card.page.translate'
      %th{ scope:'col' }= t 'card.page.review_date'
  %tbody
    - @cards.each do |card|
      %tr
        %th= card.original_text
        %th= card.translated_text
        %th= card.review_date.strftime('%d-%m-%Y')
        %th= card.current_picture
        %td= link_to t('card.page.show'), card_path(card)
        %td= link_to t('card.page.destroy'), card_path(card), method: :delete, data: { confirm: t('card.js.sure?') }
        %td= link_to t('card.page.edit'), edit_card_path(card)

app/views/cards/new.html.haml
%h2= t 'card.title.create'
= render 'form'

app/views/cards/show.html.haml
%table.table.table-sm
  %thead
    %tr
      %th{ scope:'col' }= t 'card.page.original'
      %th{ scope:'col' }= t 'card.page.translate'
      %th{ scope:'col' }= t 'card.page.review_date'
  %tbody
    %tr
      %th= @card.original_text
      %th= @card.translated_text
      %th= @card.review_date.strftime('%d-%m-%Y')
      %th= @card.current_picture
      %td= link_to t('card.page.destroy'), card_path(@card), method: :delete, data: { confirm: t('card.js.sure?') }
      %td= link_to t('card.page.edit'), edit_card_path(@card)

app/views/decks/_form.html.haml
.row.justify-content-center
  = simple_form_for(@deck, defaults: { required: false }) do |f|
    .field.text-center
      = f.input :name, label: false
      = f.input :current
      %br= f.submit t('card.button.save'), class: "btn btn-primary"

app/views/decks/edit.html.haml
%h2= t'deck.page.editing'
= render 'form'

app/views/decks/index.html.haml
%h2= t('deck.page.all')
%table.table.table-striped
  %thead
    %tr
      %th{ scope:'col' }= t('deck.page.name')
      %th{ scope:'col' }= t('deck.page.current')
  %tbody
    - @decks.each do |deck|
      %tr
        %th= deck.name
        %th= deck.current
        %td= link_to t('deck.page.show'), deck_path(deck)
        %td= link_to t('deck.page.edit'), edit_deck_path(deck)
        %td= link_to t('deck.page.destroy'), deck_path(deck), method: :delete

app/views/decks/new.html.haml
%h2= t'deck.page.creating'
= render 'form'

app/views/decks/show.html.haml
%h2= @deck.name
%table.table.table-striped
  %thead
    %tr
      %th{ scope:'col' }= t 'card.page.original'
      %th{ scope:'col' }= t 'card.page.translate'
      %th{ scope:'col' }= t 'card.page.review_date'
  %tbody
    - @deck.cards.each do |card|
      %tr
        %th= card.original_text
        %th= card.translated_text
        %th= card.review_date.strftime('%d-%m-%Y')
        %th= card.decorate.current_picture(:thumb)
        %td= link_to t('card.page.destroy'), card_path(card), method: :delete, data: { confirm: t('card.js.sure?') }
        %td= link_to t('card.page.edit'), edit_card_path(card)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type" }/
    %title= t 'header.title'
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %link{ crossorigin: "anonymous", href: "https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css",integrity: "sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2", rel: "stylesheet" }/

  %body
    %header
      .container
        %nav.navbar.navbar-expand-lg.navbar-light
          = link_to t('header.title'), root_path, class:"navbar", id:"logo"
          %button.navbar-toggler(aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" data-target="#navbarSupportedContent" data-toggle="collapse" type="button")
            %span.navbar-toggler-icon
          .collapse.navbar-collapse#navbarSupportedContent
            %ul.navbar-nav.navigation-links.ml-auto
              - if current_user
                %li.nav-item.nav-link= link_to t('user.button.edit'), edit_user_path(current_user.id), id: "links"
                %li.nav-item.nav-link= link_to t('user.button.log_out'), :logout, method: :post, id: "links"
              - else
                %li.nav-item.nav-link= link_to t('user.button.sign_in'), new_user_path, id: "links"
                %li.nav-item.nav-link= link_to t('user.button.log_in'), :login, id: "links"
                %li.nav-item.nav-link= link_to t('user.page.gh_login'), auth_at_provider_path(:provider => :github), id: "links"
  .container
    .row.justify-content-center
      .btn-group.justify-content-center
        = link_to t('header.add_card'), new_card_path, :class => "btn btn-outline-dark"
        = link_to t('header.all_cards'), cards_path, :class => "btn btn-outline-dark"
        = link_to t('deck.page.add'), new_deck_path, :class => "btn btn-outline-dark"
        = link_to t('deck.page.all'), decks_path, :class => "btn btn-outline-dark"
    .jumbotron
      .text-center
        - flash.each do |type, msg|
          = content_tag(:div, msg, class: "alert alert-#{type}")
      = yield

    %script{ crossorigin: "anonymous", integrity: "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN", src: "https://code.jquery.com/jquery-3.2.1.slim.min.js" }
    %script{ crossorigin: "anonymous", integrity: "sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q", src: "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" }
    %script{ crossorigin: "anonymous", integrity: "sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl", src: "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" }

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  .alert.alert-danger#error_explanation
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/testers/index.html.haml
.text-center
  - if @card
    %h2= @card.original_text
    = @card.current_picture
    = form_tag testers_path(@card), remote: true do
      = hidden_field_tag(:card_id, @card.id)
      = text_field_tag :answer
      = submit_tag t'card.button.check', class: "btn btn-light"

app/views/user_sessions/_form.html.haml
.row.justify-content-center
  = form_tag user_sessions_path, method: :post do
    .field
      .form-group.text-right
        = label_tag      :email
        = text_field_tag :email
      .form-group.text-right
        = label_tag          :password
        = password_field_tag :password
    .row.justify-content-center
      = submit_tag  t('user.button.log_in'), class: "btn btn-primary"

app/views/user_sessions/new.html.haml
%h2= t('user.page.log_in')
= render 'form'

app/views/users/_form.html.haml
.row.justify-content-center
  = simple_form_for(@user, defaults: { required: false }) do |f|
    .field.text-center
      = f.input :email
      = f.input :password
      = f.input :password_confirmation
      = f.submit t('card.button.save'), class: "btn btn-primary"

app/views/users/edit.html.haml
%h2= t('user.page.editing')
= render 'form'

app/views/users/index.html.haml
%table.table.table-striped
  %thead
    %tr
      %th= t('user.field.list')
  %tbody
    - @users.each do |user|
      %tr
        %td= user.email
        %th= link_to t('card.page.show'), user_path(user)
        %th= link_to t('card.page.destroy'), user_path(user), method: :delete, data: { confirm: t('card.js.sure?') }
        %th= link_to t('card.page.edit'), edit_user_path(user)

app/views/users/new.html.haml
%h2= t('user.page.creating')
= render 'form'

app/views/users/show.html.haml
.container
  %table
    %tr
    %tr
      %td= @user.email
      %th= link_to t('card.page.destroy'), user_path(@user), method: :delete, data: { confirm: t('card.js.sure?') }
      %th= link_to t('card.page.edit'), edit_user_path(@user)